#!/usr/bin/env bash
# Builds the fixture app, boots the simulator, and captures portrait
# screenshots of the live-frame emulator card for both fixture surfaces (a
# plain shell and an idle claude-code pane). See the landscape note near the
# bottom for why this is portrait-only.
#
# Fails (exit 1) if any expected PNG is missing or under 30 KB — the size
# floor catches a blank/black screenshot, which compresses to almost nothing.
set -euo pipefail
cd "$(dirname "$0")/.."

BUNDLE_ID="dev.itsmaleen.cmux"
SIM_UDID="C351D689-0865-4AB1-AAD2-83718721BB58" # iPhone 17 Pro
SCREENSHOTS_DIR="$(pwd)/screenshots"
MIN_BYTES=30720 # 30 KB

echo "== Building $BUNDLE_ID =="
# NOTE: this project's Swift Package dependency (SwiftTerm) requires a scheme
# for xcodebuild to integrate it correctly — a bare `-target cmux` build
# (the invocation documented elsewhere for this repo, from before this
# dependency existed) cannot resolve the package product at all: SPM/Xcode
# package integration relies on DerivedData-based build products, which
# `-project ... -target ...` without `-scheme` never uses (confirmed by
# `xcodebuild -derivedDataPath ... -project ... -target ...` itself refusing
# with "The flag -scheme ... is required when specifying -derivedDataPath").
# `-scheme cmux` (auto-generated by xcodegen) builds the exact same target
# and is the correct/only reliable way to build this project now.
xcodebuild -project cmux.xcodeproj -scheme cmux -sdk iphonesimulator26.5 -configuration Debug build

APP_PATH=$(xcodebuild -project cmux.xcodeproj -scheme cmux -sdk iphonesimulator26.5 -configuration Debug -showBuildSettings 2>/dev/null | awk -F'= ' '/ CODESIGNING_FOLDER_PATH/{print $2; exit}')
if [ -z "$APP_PATH" ] || [ ! -d "$APP_PATH" ]; then
  echo "Could not locate built .app (CODESIGNING_FOLDER_PATH empty or missing: '$APP_PATH')" >&2
  exit 1
fi
echo "App: $APP_PATH"

echo "== Booting simulator $SIM_UDID =="
xcrun simctl bootstatus "$SIM_UDID" -b >/dev/null 2>&1 || xcrun simctl boot "$SIM_UDID"
xcrun simctl bootstatus "$SIM_UDID" -b

echo "== Installing app =="
xcrun simctl install "$SIM_UDID" "$APP_PATH"

# The input bar's speech button requests microphone access on first appear;
# pre-granting it avoids the system permission sheet covering the card in
# every screenshot.
xcrun simctl privacy "$SIM_UDID" grant microphone "$BUNDLE_ID"

mkdir -p "$SCREENSHOTS_DIR"

capture() {
  local name=$1 surface=$2 extra_args=$3
  local out="$SCREENSHOTS_DIR/$name.png"
  xcrun simctl terminate "$SIM_UDID" "$BUNDLE_ID" >/dev/null 2>&1 || true
  # shellcheck disable=SC2086
  xcrun simctl launch "$SIM_UDID" "$BUNDLE_ID" -UITestFixture frames -UITestFocus "$surface" $extra_args >/dev/null
  sleep 4
  xcrun simctl io "$SIM_UDID" screenshot "$out"
  if [ ! -s "$out" ] || [ "$(stat -f%z "$out" 2>/dev/null || stat -c%s "$out")" -lt "$MIN_BYTES" ]; then
    echo "MISSING or too small: $out" >&2
    return 1
  fi
  echo "OK: $out ($(stat -f%z "$out" 2>/dev/null || stat -c%s "$out") bytes)"
}

failures=0

echo "== Shell surface (herdr:w2:p7) =="
capture "shell-portrait" "herdr:w2:p7" "" || failures=$((failures + 1))

echo "== Claude surface (herdr:w1:p1) =="
capture "claude-portrait" "herdr:w1:p1" "" || failures=$((failures + 1))

xcrun simctl terminate "$SIM_UDID" "$BUNDLE_ID" >/dev/null 2>&1 || true

# Landscape was attempted (cmuxApp.swift honours `-UITestOrientation
# landscape` via UIWindowScene.requestGeometryUpdate) but doesn't produce a
# usable shot in the simulator: `simctl io screenshot` captures the
# simulator's fixed portrait-shaped framebuffer, so a landscape geometry
# request just rotates the app's content sideways WITHIN that portrait
# canvas rather than yielding a true landscape image. Portrait only, per the
# brief's own fallback for this case.

if [ "$failures" -gt 0 ]; then
  echo "FAILED: $failures required (portrait) screenshot(s) missing or too small" >&2
  exit 1
fi

echo "All required screenshots captured in $SCREENSHOTS_DIR"
